cmd/create_github_worker.go

Currently the last release version is used as the changelog title, whereas the current (intended) release version should be used. This PR fixes this.

Use the current release for the markdown title

---

chronicle/release/summarizer/github/gh_issue.go
chronicle/release/summarizer/github/gh_issue_test.go
chronicle/release/summarizer/github/gh_pull_request.go
chronicle/release/summarizer/github/gh_pull_request_test.go
chronicle/release/summarizer/github/summarizer.go
internal/time_helper.go

There is an edge case where if an issue or PR close timestamp matches the same timestamp as the release the changelog is being generated for, then the PR/issue in question is filtered out:
```
[0000] DEBUG github owner="wagoodman" repo="chronicle-test" path="../chronicle-test"
[0000]  INFO since tag="v0.0.0" date="2022-03-23 20:24 UTC"
[0000]  INFO until tag="v0.1.0" commit="5d95ff3aba8b6619b59f85f24332bc3ab5b0ae11"
[0000] DEBUG total merged PRs discovered: 2
[0000] TRACE PR #2 filtered out: merged after 2022-03-23 20:19 UTC (merged 2022-03-23 20:19 UTC)
[0000] DEBUG PRs contributing to changelog: 1
[0000] DEBUG total closed issues discovered: 0
[0000] DEBUG issues contributing to changelog: 0
[0000]  INFO discovered changes: 1
[0000] DEBUG   └── added-feature: 1
```
The correct behavior …

Don't filter out PRs/issues that match the release tag date

---

.chronicle.yaml
chronicle/release/change/semver.go
chronicle/release/change/type.go
chronicle/release/find_next_version.go
chronicle/release/find_next_version_test.go
chronicle/release/format/markdown/presenter_test.go
chronicle/release/release.go
cmd/create.go
cmd/create_github_worker.go
cmd/next_version.go
go.mod
go.sum
internal/config/application.go
internal/config/github.go

Adds the ability to speculate what the next release version might be from the set of changes discovered. This is expressed as two new features:
1. Adding a `next-version` command
```
$ chronicle next-version .
v0.2.0
```
2. Allow the `create` command to speculate the next version instead of report "unreleased"
```
$ chronicle > /tmp/changelog-1.txt
$ chronicle -n > /tmp/changelog-2.txt
```
```diff
3c3
< ## [(Unreleased)](https://github.com/wagoodman/chronicle-test/tree/4e685278ed9a268806c4d7fe534d2d58d6ca0d70) (2022-03-24)
---
> ## [v0.2.0](https://github.com/wagoodman/chronicle-test/tree/v0.2.0) (2022-03-24)
5c5
< [Full Changelog](https://github.com/wagoodman/chronicle-test/compare/v0.1.0...4e685278ed9a268806c4d7fe534d2d58d6ca0d70)
---
> [Full …
```

Add next-version command

---

chronicle/release/summarizer/github/gh_issue.go
chronicle/release/summarizer/github/gh_issue_test.go
chronicle/release/summarizer/github/gh_pull_request.go
chronicle/release/summarizer/github/gh_pull_request_test.go
chronicle/release/summarizer/github/summarizer.go
chronicle/release/summarizer/github/summarizer_test.go

Follow up from https://github.com/anchore/chronicle/pull/27 ; we shouldn't consider PRs from the last release when making the changelog for this release.

Fix edge case for "PRs since" summarizer filter

---

.chronicle.yaml
Makefile
README.md
chronicle/release/summarizer/github/gh_pull_request.go
chronicle/release/summarizer/github/summarizer.go
chronicle/release/summarizer/github/summarizer_test.go
internal/config/github.go

A new `CHRONICLE_GITHUB_ISSUES_REQUIRE_PRS` boolean configurable to optionally only consider issues that have linked PRs that are merged as changelog entry candidates. Additionally adds configuration documentation

Add feature to require issues to have linked PRs

---

chronicle/release/find_next_version.go
chronicle/release/find_next_version_test.go
cmd/create_github_worker.go
cmd/next_version.go

In cases where there is already a release for a speculative release version, now that version will be skipped and the next best patch version will be used.

Add release-vs-tag context for next version selection

---

Makefile

Signed-off-by: Weston Steimel <weston.steimel@anchore.com>

bump bouncer to v0.4.0 and golangci-lint to v1.47.2

---

.github/dependabot.yaml

Updates our go module and GH actions used in workflows daily.

Add dependabot for gomod and GH actions

---

chronicle/release/releasers/github/summarizer.go
chronicle/release/releasers/github/summarizer_test.go
internal/config/github.go

This PR adds each PR to issue logs, e.g. the issue log format is: `<issue-title> [Issue #1234] ( [PR #1235] [<author>] )*`.

feat: output each PR# along with issues

---

chronicle/release/releasers/github/gh_issue.go
chronicle/release/releasers/github/gh_issue_test.go
chronicle/release/releasers/github/summarizer.go
internal/config/github.go

This PR changes the behavior slightly such that issues closed as unplanned with no linked PRs are not included by default in the output.

feat: hide issues closed as unplanned with no linked PRs

---

chronicle/release/change/change.go
chronicle/release/releasers/github/gh_issue.go
chronicle/release/releasers/github/gh_issue_test.go
chronicle/release/releasers/github/gh_pull_request.go
chronicle/release/releasers/github/gh_pull_request_test.go
chronicle/release/releasers/github/summarizer.go
chronicle/release/releasers/github/summarizer_test.go
cmd/create_github_worker.go
internal/config/github.go

This PR adds a section for additional changes which do not have change types, currently only including unlabeled PRs, .e.g.:
```
- chore: claim artifacthub package ownership from developer-guy [[PR #661](https://github.com/anchore/grype/pull/661)] [[developer-guy](https://github.com/developer-guy)]
- chore: update yardstick to diagnose intermittent quality gate test failures [[PR #1054](https://github.com/anchore/grype/pull/1054)] [[kzantow](https://github.com/kzantow)]
```
Closes #4

feat: add section for additional changes which do not have change types

---

chronicle/release/releasers/github/gh_issue.go
chronicle/release/releasers/github/gh_issue_test.go
chronicle/release/releasers/github/gh_pull_request_test.go
chronicle/release/releasers/github/summarizer.go
chronicle/release/releasers/github/summarizer_test.go
internal/config/github.go

This PR adds issues to the _Additional Changes_ section when they do not have any labels.
Example:
```
- Getting many warnings (empty ID, unable to read golang buildinfo, bin parsing) when running grype from command line and directing stderr to file [[Issue #1050](https://github.com/anchore/grype/issues/1050)] [[PR #1067](https://github.com/anchore/grype/pull/1067)] [[kzantow](https://github.com/kzantow)]
- chore: claim artifacthub package ownership from developer-guy [[PR #661](https://github.com/anchore/grype/pull/661)] [[developer-guy](https://github.com/developer-guy)]
- chore: update yardstick to diagnose intermittent quality gate test failures [[PR #1054](https://github.com/anchore/grype/pull/1054)] [[kzantow](https://github.com/kzantow)]
```
Closes #5

feat: include closed issues with no labels in Additional Changes section

---

.github/workflows/validations.yaml

This PR causes validation checks to run on pushes to main, which is a requirement for the release quality gate.

chore: run validations on pushes to main

---

Makefile

right now the makefile will pull the latest, but the CI cache will rarely bust the cache. This will bust the cache and pin to a specific version.

Bump chronicle version to v0.6.0

---

DEVELOPING.md
Makefile

Splits the format-related tasks in the `lint-fix` target into a new `format` target (which `lint-fix` depends on)

Add format make target 

---

.github/workflows/oss-project-board-add.yaml

Allows for automatically adding issues to the [OSS community board](https://github.com/orgs/anchore/projects/22)

Add oss community board auto-add workflow

---

internal/git/tag.go

This PR adjusts the behavior when unable to get info from a tag, chronicle will fail to speculate a version and thus things like `syft` `make release` will fail.

fix: continue on tag errors

---

chronicle/release/releasers/github/gh_issue.go
chronicle/release/releasers/github/gh_pull_request.go
chronicle/release/releasers/github/gh_pull_request_test.go
chronicle/release/releasers/github/summarizer.go

Today we fetch all issues and PRs without curtailing the search based on known release information. This PR adjusts this behavior to consider timestamps from the last release, terminating PR and issue fetching when we've reached a non-candidate (with all requests ordered by the "last updated" field).
The performance gain depends on the repo in question, since it's sensitive to the total number of PRs and issues in that repo. In the syft repo as of this writing this cuts down the time to run chronicle from 20 seconds to 2 seconds 🎉 .

Restrict fetching PRs and issues only to time range needed

---

.github/actions/bootstrap/action.yaml
.github/scripts/ci-check.sh
.github/scripts/trigger-release.sh
.github/workflows/release.yaml
.github/workflows/validations.yaml
.goreleaser.yaml
Makefile
RELEASE.md

This brings the latest CI patterns from syft into this repo, specifically:
- use a single bootstrap action and reuse in multiple jobs
- add `make release` target to trigger tagging to be done in the workflow (not locally)
- restricts GITHUB_TOKEN permissions to read only by default
- upgrades job runners to ubuntu 22.04
- replaces draft-only goreleaser config with direct-to-publish release workflow
This makes additional pattern changes:
- swaps to using annotated tags instead of lightweight tags
- swaps the chronicle version used in the pipeline to the current branch

Upgrade CI workflows

---

.github/workflows/dependabot-auto-merge.yaml

Manually reviewing these PRs has become a chore, and there's good automated testing in place.
See anchore/quill#220 and anchore/quill#221

chore: enable dependabot prs to auto-merge

---

.github/workflows/dependabot-automation.yaml

Now that the shared workflow for auto approving dependabot PRs has been checked, this bumps from the feature branch to the main branch.

Bump shared workflow to main branch

---

.github/actions/bootstrap/action.yaml
.golangci.yaml
Makefile
cmd/chronicle/cli/commands/next_version.go
go.mod

Update to building with go [1.24.x](https://tip.golang.org/doc/go1.24) so that the main module version gets set during go build

feat: update to go 1.24.x

---

.github/workflows/codeql-analysis.yml

This PR updates the CodeQL permissions to be able to upload a security report without failures such as: https://github.com/anchore/chronicle/actions/runs/15168423589/job/42652175541#step:6:293

chore: update codeql permissions
